- name: Deploy to Azure Container Instance
  uses: azure/cli@v1
  with:
    inlineScript: |
      az container create \
        --resource-group ${{ secrets.AZURE_RG }} \
        --name ${{ secrets.CONTAINER_NAME }} \
        --image ${{ secrets.ACR_NAME }}/node_cicd_image:latest \
        --registry-login-server ${{ secrets.ACR_NAME }} \
        --registry-username ${{ secrets.ACR_USERNAME }} \
        --registry-password ${{ secrets.ACR_PASSWORD }} \
        --dns-name-label ${{ secrets.CONTAINER_NAME }} \
        --ports 3000 \
        --os-type Linux \
        --location ${{ secrets.AZURE_LOCATION }} \
        --restart-policy OnFailure
